#####################################################
## Default colour scheme ############################
#####################################################

## Domain: [red, green, blue] (colour value: 0-1) ###

general: [0.2, 0.8, 0.4]
laboratory: [0.8, 0.2, 0.4]
pediatrics: [0.25, 0.6, 0.96]

anaesthesiology: [0.5, 0.5, 0.5]
emergency-medicine: [0.5, 0.5, 0.5]
endocrinology: [0.5, 0.5, 0.5]
gastroenterology: [0.5, 0.5, 0.5]
gynecology: [0.5, 0.5, 0.5]
neurology: [0.5, 0.5, 0.5]
orthopedics: [0.5, 0.5, 0.5]
surgery: [0.5, 0.5, 0.5]